name: Run Full Regression - all suites
permissions:
  contents: write
on: [workflow_dispatch]

jobs:
  execute-smoke:
    uses: ./.github/workflows/smoke-test.yml
    with: { suite: testng-smoke.xml }
    secrets: inherit

  execute-integration:
    needs: execute-smoke
    uses: ./.github/workflows/smoke-test.yml
    with: { suite: testng-integration.xml }
    secrets: inherit

  execute-e2e:
    needs: execute-integration
    uses: ./.github/workflows/smoke-test.yml
    with: { suite: testng-e2e.xml }
    secrets: inherit

  publish-report:
    needs: [execute-smoke, execute-integration, execute-e2e]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          path: merged-results
          merge-multiple: true

      - name: Push results to Allure
        uses: ./.github/actions/to-allure
        with:
          run-label: ${{ github.run_number }}-full-regression
          allure-results-path: merged-results